### ISSUE TITLE
[DATA]Cloud_Platform

### ISSUE THREAD

**Issue by beltocas** [unmsmfisi-socialapplication/social_app#257]
folder restructuring

**Comment by ZDev-19** [comment]
### **Data folder new Structure**
In order to integrate Cloud platform management , data folder has a new structure:

- models_testing: This folder contains all Jupyter notebooks that are only for features testing
- cloud_platform: This folder will contain all files like JSON and python scripts in order to manage Google Drive in python (Test only)
- Official model scripts will be temporary storage in the folder root (data).

**Comment by ZDev-19** [comment]
### **Issue segmentation**
The cloud platform integration is distributed in six issues : 

- Issue #266 
- Issue #267 
- Issue #264 
- Issue #261 
- Issue #262 
- Issue #263 

All issues deadline are established on October 1
