### ISSUE TITLE
[DATA] Define processes for file download and searching

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#262]

**Comment by orlando2400** [comment]
Author: @orlando2400
Date Created: [05/10/2023]

The script uses 'Pydrive2' to perform actions on files entered in Google Drive in order to have information about any changes and also download it according to the name of the file.

**Functions:**

1. search : 
Function to search for a file in Google Drive according to a given name.

1. download_file:
Function to download a file according to its name and path to save the download locally.

1. test:
This function performs a unit test on the download_file function using a preset name and path.

**Comment by ZDev-19** [comment]
This issue was completed according to team meeting held on 10/10
