### ISSUE TITLE
[DATA] Parameterize model variables in sentiment analysis

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#423]

**Comment by syntx8** [comment]
# Parameterize model variables in Sentiment Analysis
Modifications were made to the code to parameterize certain settings and variables, making the script more flexible and easier to adapt to different scenarios. Here is an explanation of what was done in each part of the code:

### 1. Definition of Parametrized Variables: 
- At the beginning of the script, parametrized variables were defined, which contain specific values that can be adjusted according to the needs. These variables include the CSV file path, column names, seed, split percentages, model parameters, and metric names. This makes the script more reusable and configurable.

### 2. CSV File Reading: 
- The fileUrl variable was used instead of a fixed file URL. This allows you to change the path of the CSV file without modifying the main code of the script.

### 3. Data Processing: 
- Parametrized variables are used instead of literal values in the data preprocessing process, such as column renaming and regular expressions to clean tweets. This makes the code clearer and easier to maintain.

### 4. Data Splitting: 
- Parametrized variables TRAIN_RATIO and TEST_RATIO are used to define the percentages for splitting between training and testing sets. The seed is also parametrized.

### 5. Model Evaluation: 
- The metrics used for model evaluation are defined using parametrized variables, such as ROC_METRIC_NAME, F1_METRIC_NAME, and ACCURACY_METRIC_NAME. This allows you to change the metrics without modifying the main code.

### 6. Logistic Regression Model: 
- The parameters of the logistic regression model are set using parametrized variables, such as MAX_ITER_LR. Additionally, the number of folds in cross-validation is parametrized with NUM_FOLDS.

### 7. Use of Parametrized Variables: 
- Throughout the script, parametrized variables are used instead of literal values, making it easier to configure and adapt the script to different situations.

### 8. Final Configuration: 
- The main section of the script uses the parametrized variables and calls functions with the appropriate arguments, making the code more readable and configurable.
