### ISSUE TITLE
[DATA] Search Google Cloud Platorm services for proposed workflow

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#424]
### **Objective**
Rearch about the Google Cloud Platform services for workflow design made in #411

**Comment by EGH2019** [comment]
According to the diagram, it is true that for AWS, you can use 3 services, which consist of S3, Lambda, and Step Functions. In this case, for GCP, you could use 2, which would be GCS (Google Cloud Storage) and Composer. This is because Composer allows you to create Python code boxes and orchestrate them, so it would make the creation of that workflow much easier.

**Comment by EGH2019** [comment]
# Google Services

## Google Cloud Storage
Google Cloud Storage (GCS) is a scalable, durable, and highly available object storage service that can be used to store a variety of data, including text, images, videos, and code.

### Cost
The cost of using GCS depends on the amount of data that you store and the region in which you store it.

### Pricing by region

### South America

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/54995563/44c706c5-e422-4d6c-94cc-dec81810d8ee)

### North America



![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/54995563/eec39947-f9e9-4638-b4bf-f081df799b46)

**Comment by ZDev-19** [comment]
### **Closing issue due to complete documentation**
