### ISSUE TITLE
[DATA] Documentation of team data data types

### ISSUE THREAD

**Issue by baneuser** [unmsmfisi-socialapplication/social_app#586]
Documentation of data types required for each team member. Send data formats for the models made. Or any other requirement that needs backend

**Comment by francosilva25** [comment]
Hello data team,

I would appreciate that the first information you require is something general, in order to advance the generation of the table, SQL queries and how to send the information as quickly as possible. I remain attentive to the updates of this issue. After that you can generate more requirements for the specific information you need for each member of your team.

Franco Silva.

**Comment by gustavo-guerreros1** [comment]
Specific columns in the database:

ID: Identifier for each record.
FORMATTED_CONTENT: The content of the text message to be used as a feature for the logistic regression model.
CLASS: Binary indicator (0 or 1) denoting whether the content is spam or not.
Technical justification: These columns are essential for training and evaluating the spam detection logistic regression model. The ID provides a identifier, the FORMATTED_CONTENT is the textual feature that will be used for analysis, and the CLASS column provides the class labels that are critical for supervised training.

Clean and preprocessed data:

Ensure that the data is clean and preprocessed, i.e., without null values, normalized text, and without unwanted special characters.
Technical justification: Clean and preprocessed data ensures consistent and high-quality input for the logistic regression model. This helps to avoid issues during training and improves the model's accuracy.

Compatible data format:

Request that the data be delivered in a compatible format such as relational database.
Technical justification: A compatible data format simplifies the data loading and preprocessing process, enabling smoother integration with the logistic regression model.

Separate training and test data:

Request separate data sets for training and testing, with an appropriate ratio for each.
Technical justification: Separating data sets into training and testing is crucial for evaluating the model's ability to generalize to unseen data and avoid overfitting.

Regular data updates:

Request periodic updates of the data to keep the model up-to-date and adaptable to changes in spam patterns.
Technical justification: Regular data updates allow the logistic regression model to adjust to changing trends and ensure its effectiveness over time.

**Comment by syntx8** [comment]
# Subject: Request to create a table in the database for sentiment analysis of posts.

### **Backend Team**,
@francosilva25 

I am writing to request the creation of a table in our database specifically designed to conduct sentiment analysis on SocialApp posts. The purpose of this table is to store and manage the data provided in a .csv file with the following structure:

## Specific Columns in the Database
- **clean_text:** This field will contain the clean text of the posts, which will be the primary feature used in our sentiment analysis process.

- **category:** In this field, categories representing the sentiment of the posts will be stored. These categories are expressed as numerical values, for example, `-1 for negative, 0 for neutral, and 1 for positive`.

For a better understanding, here is an example of the first row from the .csv file that will serve as the basis for this table:

| clean_text | category |
| --- | --- |
| when modi promised “minimum government maximum governance” expected him begin the difficult job reforming the state why does take years get justice state should and not business and should exit psus and temples | -1 |

## Reasons for this request
The creation of this table is essential for our SocialApp sentiment analysis project. It will allow us to store and efficiently manage the collected data, which is crucial for achieving the project's objectives.

### Details to consider:

- The table should be designed and optimized to enable efficient searches and queries, as we handle large volumes of data.

- Since we plan to continuously collect data, it is essential that the table is designed with the capability for periodic data updates in mind.

Please provide an estimated date when this table will be available in the database. If you need more information or additional clarifications to proceed with this request, please do not hesitate to contact me through this "issue."

**Comment by orlando2400** [comment]
**Hello Backend Team**,

You are requested to create a table to classify the posts in SocialApp, the purpose is to have a data structure as mentioned below.

## Required columns in the database:

- post_text: Field of the table that will contain the text of the post to later classify it in a particular topic using the implemented classifier.

- label: Field of the table that will contain the topic referred to the post, in the developed classifier I considered these topics: 'travel', 'lifestyle', 'food', 'other'.
 
## Reasons for this request
The requested table is important for the classification of posts so that in another section certain graphs can be created using this post classification. Without further support with the above mentioned.

> **If you have any questions related to this comment, please contact me by following the comments flow.**

**Comment by francosilva25** [comment]
Hi @syntx8 @orlando2400 @gustavo-guerreros1 

With respect to the users posts, an API will be generated that will send the information by a start and end date.

Using this API you will be able to upload the information to your database.

We will be reviewing it with my team and we will specify its use in an issue.

Kind regards,

Franco Silva

**Comment by francosilva25** [comment]
Hello Data Team, we already have structured the function that we are going to consume in the API to send the information of the posts. If you need any additional field, please let us know as soon as possible.

You can check it in this issue: #640 

We are already building the API.

Kind regards,

Franco Silva

**Comment by baneuser** [comment]
Dear team,

It has been a collaborative and enriching journey working together on documenting data types for our projects. I greatly appreciate the valuable contributions of each of you:

Me: Providing documentation of the data types needed for each team member and ensuring compatibility with backend models.
@francosilva25: Facilitating the generation of tables and SQL queries crucial to advance our analyses. Furthermore, the initiative to create an API for information transfer is a great step forward.
@gustavo-guerreros1: Identifying essential columns in the database and highlighting the importance of clean and preprocessed data for model accuracy.
@syntx8 and @orlando2400: Raising specific needs for table creation in the context of sentiment analysis and post classification.
The synergy between our teams has been fundamental to define key requirements, ensuring the quality of the data and the efficiency of our models. We have established clear guidelines for the structure of the tables and the continuity in updating data.

I greatly appreciate your dedication and continued collaboration!

Sincerely,
